#!/bin/bash

set -e
set -x

rsync -v -a /source/ /build/ --exclude .git --exclude log --exclude tmp --exclude repos --exclude public/system

echo "--- bundle install"
bundle check --path /cache/bundler || bundle install --deployment --path /cache/bundler -j 8

echo "--- setup test database"
time bundle exec rake db:create
time bundle exec rake db:test:prepare

echo "--- rspec"
time bundle exec rspec spec
