#!/bin/bash

set -e
set -x

export RAILS_ENV=test

rsync -a /source/ /build/ --exclude log --exclude tmp --exclude repos --exclude public/system
mkdir -p vendor/bundle
gunzip -c artifacts/bundle.gz > vendor/bundle

cd /build

echo "--- start postgresql and redis"
sudo service postgresql start
sudo service redis-server start

echo "--- bundle check"
bundle check --path vendor/bundle

echo "--- setup test database"
time bundle exec rake db:create
time bundle exec rake db:test:prepare

echo "--- git submodules"
git submodule update --init

echo "--- rspec"
time bundle exec rspec spec
